apiVersion: lan.party/v1
kind: Points
metadata:
  name: tournament-points
  labels:
    system: tournament
spec:
  name: "Tournament Points"
  description: "Point allocation system for tournament placements and participation"
  system: "tournament"
  rules:
    - event: "Tournament Win"
      condition: "1st place"
      points: 500
      description: "Winner of any tournament"
    - event: "Tournament Participation"
      condition: "participation"
      points: 50
      description: "Participation in any tournament"

---
apiVersion: lan.party/v1
kind: Points
metadata:
  name: points
  labels:
    system: overall
spec:
  name: "Overall LAN Party Points System"
  description: "Comprehensive point system for the entire event"
  system: "overall"
  rules:
    - event: "Won a Contest"
      condition: "won a contest"
      points: 250
      description: "Bonus points for winning a contest"
    - event: "Entered a Bounty"
      condition: "entered a bounty"
      points: 250
      description: "Points for entering a bounty"
    - event: "Mike said so 10"
      condition: "Mike said so 10"
      points: 10
      description: "Points for Mike said so 10"
    - event: "Mike said so 10"
      condition: "Mike said so 25"
      points: 25
      description: "Points for Mike said so 10"
    - event: "Mike said so 10"
      condition: "Mike said so 50"
      points: 50
      description: "Points for Mike said so 50"
