apiVersion: lan.party/v1
kind: Schedule
metadata:
  name: rgb-lan-8-schedule
  labels:
    event: rgb-lan-8
spec:
  name: "RGB LAN 8 Schedule"
  description: "Complete schedule for RGB LAN 8 event (Sept 6-8, 2025)"
  eventRef: "rgb-lan-8"
  tournaments: [
    "mario-kart-world-ffa", "clefairy-says-ffa", "counter-strike-2-arms-race", 
    "rocket-league-3v3", "team-fortress-2-6v6", "super-smash-bros-ultimate-1v1",
    "wii-tennis-2v2", "halo-reach-ffa", "pubg-ffa", "marvel-vs-capcom-2-1v1",
    "fall-guys-ffa", "counter-strike-2-wingman-2v2", "super-smash-bros-melee-1v1",
    "ut2004-big-game", "sticky-cats-ffa", "mvp-tournament"
  ]
  activities: [
    "speedrunning-stream", "super-bomberman-2-ffa", "marvel-rivals-6v6", 
    "mystery-game", "midnight-madness", "raffle"
  ]
  events:
    # Day 1 - Friday, September 6, 2025
    - name: "LAN STARTS!"
      description: "Event opening and setup begins"
      startTime: "2025-09-06T10:00:00Z"
      endTime: "2025-09-06T11:00:00Z"
      location: "Main venue"
      type: "ceremony"
      priority: 10

    - name: "Mario Kart World (FFA)"
      description: "Free-for-all Mario Kart World tournament"
      startTime: "2025-09-06T13:00:00Z"
      endTime: "2025-09-06T14:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "mario-kart-world-ffa"

    - name: "Speedrunning TBA"
      description: "Speedrunning activities - game to be announced"
      startTime: "2025-09-06T13:00:00Z"
      endTime: "2025-09-06T14:00:00Z"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Clefairy Says (FFA)"
      description: "Free-for-all Clefairy Says tournament"
      startTime: "2025-09-06T15:00:00Z"
      endTime: "2025-09-06T16:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "clefairy-says-ffa"

    - name: "Speedrunning TBA"
      description: "Speedrunning activities - game to be announced"
      startTime: "2025-09-06T15:00:00Z"
      endTime: "2025-09-06T16:00:00Z"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Counter-Strike 2 Arms Race (FFA)"
      description: "Free-for-all Counter-Strike 2 Arms Race tournament"
      startTime: "2025-09-06T16:00:00Z"
      endTime: "2025-09-06T17:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "counter-strike-2-arms-race"

    - name: "Rocket League (3v3) Random Teams"
      description: "3v3 Rocket League tournament with random team assignments"
      startTime: "2025-09-06T17:00:00Z"
      endTime: "2025-09-06T18:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "rocket-league-3v3"

    - name: "TF2 Team Signup Deadline"
      description: "Team Fortress 2 team signup deadline at 6:30 PM"
      startTime: "2025-09-06T18:00:00Z"
      endTime: "2025-09-06T18:30:00Z"
      location: "Registration desk"
      type: "registration"

    - name: "Super Bomberman 2 (FFA)"
      description: "Free-for-all Super Bomberman 2 tournament"
      startTime: "2025-09-06T18:00:00Z"
      endTime: "2025-09-06T19:00:00Z"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "super-bomberman-2-ffa"

    - name: "Team Fortress 2 (6v6) Group Stage"
      description: "Team Fortress 2 6v6 tournament group stage"
      startTime: "2025-09-06T19:00:00Z"
      endTime: "2025-09-06T20:00:00Z"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "team-fortress-2-6v6"
      priority: 8

    - name: "Super Smash Bros. Ultimate (1v1)"
      description: "1v1 Super Smash Bros. Ultimate tournament"
      startTime: "2025-09-06T21:00:00Z"
      endTime: "2025-09-06T22:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "super-smash-bros-ultimate-1v1"

    - name: "Speedrunning TBA"
      description: "Speedrunning activities - game to be announced"
      startTime: "2025-09-06T21:00:00Z"
      endTime: "2025-09-06T22:00:00Z"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Wii Tennis (2v2)"
      description: "2v2 Wii Tennis tournament"
      startTime: "2025-09-06T22:00:00Z"
      endTime: "2025-09-06T23:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "wii-tennis-2v2"

    - name: "Speedrunning TBA"
      description: "Speedrunning activities - game to be announced"
      startTime: "2025-09-06T22:00:00Z"
      endTime: "2025-09-06T23:00:00Z"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "MIDNIGHT MADNESS!"
      description: "Special midnight event"
      startTime: "2025-09-07T00:00:00Z"
      endTime: "2025-09-07T01:00:00Z"
      location: "Main stage"
      type: "special"
      relatedTo: "midnight-madness"
      priority: 9

    # Day 2 - Saturday, September 7, 2025
    - name: "Team Fortress 2 (6v6) Double Elimination Bracket Stage"
      description: "Team Fortress 2 6v6 tournament bracket stage"
      startTime: "2025-09-07T11:00:00Z"
      endTime: "2025-09-07T13:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "team-fortress-2-6v6"
      priority: 8

    - name: "Marvel Rivals (6v6)"
      description: "6v6 Marvel Rivals tournament"
      startTime: "2025-09-07T13:00:00Z"
      endTime: "2025-09-07T14:00:00Z"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "marvel-rivals-6v6"

    - name: "Halo: Reach [MCC] (FFA)"
      description: "Free-for-all Halo: Reach Master Chief Collection tournament"
      startTime: "2025-09-07T14:00:00Z"
      endTime: "2025-09-07T15:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "halo-reach-ffa"

    - name: "PUBG (FFA)"
      description: "Free-for-all PUBG tournament"
      startTime: "2025-09-07T16:00:00Z"
      endTime: "2025-09-07T17:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "pubg-ffa"

    - name: "Marvel vs Capcom 2 (1v1)"
      description: "1v1 Marvel vs Capcom 2 tournament"
      startTime: "2025-09-07T17:00:00Z"
      endTime: "2025-09-07T18:00:00Z"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "marvel-vs-capcom-2-1v1"

    - name: "Speedrunning TBA"
      description: "Speedrunning activities - game to be announced"
      startTime: "2025-09-07T17:00:00Z"
      endTime: "2025-09-07T18:00:00Z"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Fall Guys (FFA)"
      description: "Free-for-all Fall Guys tournament"
      startTime: "2025-09-07T18:00:00Z"
      endTime: "2025-09-07T19:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "fall-guys-ffa"

    - name: "Counter-Strike 2 Wingman (2v2)"
      description: "2v2 Counter-Strike 2 Wingman tournament"
      startTime: "2025-09-07T19:00:00Z"
      endTime: "2025-09-07T20:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "counter-strike-2-wingman-2v2"

    - name: "Super Smash Bros. Melee (1v1)"
      description: "1v1 Super Smash Bros. Melee tournament"
      startTime: "2025-09-07T20:00:00Z"
      endTime: "2025-09-07T21:00:00Z"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "super-smash-bros-melee-1v1"

    - name: "Speedrunning TBA"
      description: "Speedrunning activities - game to be announced"
      startTime: "2025-09-07T20:00:00Z"
      endTime: "2025-09-07T21:00:00Z"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "UT2004 (big game - everyone join!)"
      description: "Unreal Tournament 2004 big multiplayer game"
      startTime: "2025-09-07T22:00:00Z"
      endTime: "2025-09-07T23:00:00Z"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "ut2004-big-game"
      priority: 7

    - name: "Mystery game :)"
      description: "Mystery game tournament - surprise game to be revealed!"
      startTime: "2025-09-07T23:00:00Z" 
      endTime: "2025-09-08T00:00:00Z"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "mystery-game"

    - name: "Speedrunning TBA"
      description: "Speedrunning activities - game to be announced"
      startTime: "2025-09-07T23:00:00Z"
      endTime: "2025-09-08T00:00:00Z"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "MIDNIGHT MADNESS!"
      description: "Special midnight event"
      startTime: "2025-09-08T00:00:00Z"
      endTime: "2025-09-08T01:00:00Z"
      location: "Main stage"
      type: "special"
      relatedTo: "midnight-madness"
      priority: 9

    # Day 3 - Sunday, September 8, 2025
    - name: "🐱Sticky Cats🐱 (FFA)"
      description: "Free-for-all Sticky Cats tournament"
      startTime: "2025-09-08T10:00:00Z"
      endTime: "2025-09-08T11:00:00Z"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "sticky-cats-ffa"

    - name: "Speedrunning TBA"
      description: "Speedrunning activities - game to be announced"
      startTime: "2025-09-08T10:00:00Z"
      endTime: "2025-09-08T11:00:00Z"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "RAFFLE!"
      description: "Prize raffle event"
      startTime: "2025-09-08T11:00:00Z"
      endTime: "2025-09-08T12:00:00Z"
      location: "Main stage"
      type: "special"
      relatedTo: "raffle"
      priority: 8

    - name: "MVP Tournament"
      description: "Most Valuable Player tournament - final championship"
      startTime: "2025-09-08T12:00:00Z"
      endTime: "2025-09-08T16:00:00Z"
      location: "Main tournament area"
      type: "tournament"
      relatedTo: "mvp-tournament"
      priority: 10

    - name: "LAN ENDS!"
      description: "Event conclusion and cleanup"
      startTime: "2025-09-08T16:00:00Z"
      endTime: "2025-09-08T17:00:00Z"
      location: "Main venue"
      type: "ceremony"
      priority: 10
