apiVersion: lan.party/v1
kind: Schedule
metadata:
  name: rgb-lan-8-schedule
  labels:
    event: rgb-lan-8
spec:
  name: "RGB LAN 8 Schedule"
  description: "Complete schedule for RGB LAN 8 event (Sept 5-7, 2025)"
  eventRef: "rgb-lan-8"
  tournaments: [
    "mario-kart-world-ffa", "clefairy-says-ffa", "counter-strike-2-arms-race", 
    "counter-strike-2-wingman-2v2", "team-fortress-2-6v6", "super-bomberman-2-ffa",
    "pubg-ffa", "nidhogg-1v1", "marvel-rivals-6v6", "rocket-league-2v2",
    "beyblade-x", "ut2004-big-game", "marvel-vs-capcom-2-1v1", "fall-guys-ffa",
    "halo-reach-mcc-ffa", "super-smash-bros-melee-1v1", "wii-tennis-2v2",
    "mystery-game", "sticky-cats-ffa", "mvp-tournament"
  ]
  activities: [
    "speedrunning-stream", "wildcard-2v2", "keep-talking", "invisigun",
    "screencheat", "be-quiet-case-race", "midnight-madness", "raffle"
  ]
  events:
    # Day 1 - Friday, September 5, 2025
    - name: "LAN STARTS!"
      description: "Event opening and setup begins"
      startTime: "2025-09-05T10:00:00-05:00"
      endTime: "2025-09-07T11:00:00-05:00"
      location: "Main venue"
      type: "ceremony"
      priority: 10

    - name: "Setup/Registration"
      description: "Participant check-in and initial setup"
      startTime: "2025-09-05T11:00:00-05:00"
      endTime: "2025-09-05T12:00:00-05:00"
      location: "Registration area"
      type: "registration"

    - name: "Setup/Registration"
      description: "Participant check-in and initial setup"
      startTime: "2025-09-05T12:00:00-05:00"
      endTime: "2025-09-05T13:00:00-05:00"
      location: "Registration area"
      type: "registration"

    - name: "Mario Kart World (FFA)"
      description: "Free-for-all Mario Kart World tournament"
      startTime: "2025-09-05T13:00:00-05:00"
      endTime: "2025-09-05T14:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "mario-kart-world-ffa"

    - name: "OpenGOAL: Jak 2 Speedrun"
      description: "Speedrunning event for OpenGOAL: Jak 2"
      startTime: "2025-09-05T13:00:00-05:00"
      endTime: "2025-09-05T14:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Wildcard 2v2 Tournament"
      description: "Points activity: Wildcard 2v2 tournament"
      startTime: "2025-09-05T13:00:00-05:00"
      endTime: "2025-09-05T14:00:00-05:00"
      location: "Points area"
      type: "activity"

    - name: "Break/Open Gaming"
      description: "Open gaming and break time"
      startTime: "2025-09-05T14:00:00-05:00"
      endTime: "2025-09-05T15:00:00-05:00"
      location: "Various areas"
      type: "break"

    - name: "Clefairy Says (FFA)"
      description: "Free-for-all Clefairy Says tournament"
      startTime: "2025-09-05T15:00:00-05:00"
      endTime: "2025-09-05T16:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "clefairy-says-ffa"

    - name: "A Hat in Time Speedrun"
      description: "Speedrunning event for A Hat in Time"
      startTime: "2025-09-05T15:00:00-05:00"
      endTime: "2025-09-05T16:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Counter-Strike 2 Arms Race (FFA)"
      description: "Free-for-all Counter-Strike 2 Arms Race tournament"
      startTime: "2025-09-05T16:00:00-05:00"
      endTime: "2025-09-05T17:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "counter-strike-2-arms-race"

    - name: "Hikaru no Go Speedrun"
      description: "Speedrunning event for Hikaru no Go"
      startTime: "2025-09-05T16:00:00-05:00"
      endTime: "2025-09-05T17:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Counter-Strike 2 Wingman (2v2)"
      description: "2v2 Counter-Strike 2 Wingman tournament"
      startTime: "2025-09-05T17:00:00-05:00"
      endTime: "2025-09-05T18:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "counter-strike-2-wingman-2v2"

    - name: "Monster Truck Rally Speedrun"
      description: "Speedrunning event for Monster Truck Rally"
      startTime: "2025-09-05T17:00:00-05:00"
      endTime: "2025-09-05T18:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "TF2 Team Signup Deadline"
      description: "Team Fortress 2 team signup deadline at 6:30 PM"
      startTime: "2025-09-05T18:00:00-05:00"
      endTime: "2025-09-05T18:30:00-05:00"
      location: "Registration desk"
      type: "registration"

    - name: "Super Bomberman 2 (FFA)"
      description: "Free-for-all Super Bomberman 2 tournament"
      startTime: "2025-09-05T18:00:00-05:00"
      endTime: "2025-09-05T19:00:00-05:00"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "super-bomberman-2-ffa"

    - name: "Hollow Knight Speedrun"
      description: "Speedrunning event for Hollow Knight"
      startTime: "2025-09-05T18:00:00-05:00"
      endTime: "2025-09-05T19:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Team Fortress 2 (6v6) Group Stage"
      description: "Team Fortress 2 6v6 tournament group stage"
      startTime: "2025-09-05T19:00:00-05:00"
      endTime: "2025-09-05T20:00:00-05:00"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "team-fortress-2-6v6"
      priority: 8

    - name: "BAPBAP Speedrun"
      description: "Speedrunning event for BAPBAP"
      startTime: "2025-09-05T19:00:00-05:00"
      endTime: "2025-09-05T20:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "PUBG (FFA)"
      description: "Free-for-all PUBG tournament"
      startTime: "2025-09-05T20:00:00-05:00"
      endTime: "2025-09-05T21:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "pubg-ffa"

    - name: "Keep Talking Stage Event"
      description: "Keep Talking stage activity"
      startTime: "2025-09-05T21:00:00-05:00"
      endTime: "2025-09-05T22:00:00-05:00"
      location: "Main stage"
      type: "activity"

    - name: "Nidhogg (1v1)"
      description: "1v1 Nidhogg tournament"
      startTime: "2025-09-05T22:00:00-05:00"
      endTime: "2025-09-05T23:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"

    - name: "Late Night Gaming"
      description: "Late night gaming session"
      startTime: "2025-09-05T23:00:00-05:00"
      endTime: "2025-09-06T00:00:00-05:00"
      location: "Various areas"
      type: "activity"

    - name: "MIDNIGHT MADNESS!"
      description: "Special midnight event"
      startTime: "2025-09-06T00:00:00-05:00"
      endTime: "2025-09-06T01:00:00-05:00"
      location: "Main stage"
      type: "special"
      relatedTo: "midnight-madness"
      priority: 9

    # Day 2 - Saturday, September 6, 2025
    - name: "Team Fortress 2 (6v6) Double Elimination Bracket Stage"
      description: "Team Fortress 2 6v6 tournament bracket stage"
      startTime: "2025-09-06T11:00:00-05:00"
      endTime: "2025-09-06T12:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "team-fortress-2-6v6"
      priority: 8

    - name: "TAGPRO Speedrun"
      description: "Speedrunning event for TAGPRO"
      startTime: "2025-09-06T11:00:00-05:00"
      endTime: "2025-09-06T12:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Marvel Rivals (6v6)"
      description: "6v6 Marvel Rivals tournament"
      startTime: "2025-09-06T12:00:00-05:00"
      endTime: "2025-09-06T13:00:00-05:00"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "marvel-rivals-6v6"

    - name: "Rocket League (2v2)"
      description: "2v2 Rocket League tournament"
      startTime: "2025-09-06T13:00:00-05:00"
      endTime: "2025-09-06T14:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"

    - name: "Nintendo Switch 2 Welcome Tour Speedrun"
      description: "Speedrunning event for Nintendo Switch 2 Welcome Tour"
      startTime: "2025-09-06T13:00:00-05:00"
      endTime: "2025-09-06T14:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Invisigun Stage Event"
      description: "Invisigun stage activity"
      startTime: "2025-09-06T13:00:00-05:00"
      endTime: "2025-09-06T14:00:00-05:00"
      location: "Main stage"
      type: "activity"

    - name: "Beyblade X (Hosted by Fearbola)"
      description: "Beyblade X tournament hosted by Fearbola"
      startTime: "2025-09-06T14:00:00-05:00"
      endTime: "2025-09-06T15:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"

    - name: "Pikmin 2 Speedrun"
      description: "Speedrunning event for Pikmin 2"
      startTime: "2025-09-06T14:00:00-05:00"
      endTime: "2025-09-06T15:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Spyro the Dragon Speedrun"
      description: "Speedrunning event for Spyro the Dragon"
      startTime: "2025-09-06T15:00:00-05:00"
      endTime: "2025-09-06T16:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Screencheat Stage Event"
      description: "Screencheat stage activity"
      startTime: "2025-09-06T15:00:00-05:00"
      endTime: "2025-09-06T16:00:00-05:00"
      location: "Main stage"
      type: "activity"

    - name: "UT2004 (big game - everyone join!)"
      description: "Unreal Tournament 2004 big multiplayer game"
      startTime: "2025-09-06T16:00:00-05:00"
      endTime: "2025-09-06T17:00:00-05:00"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "ut2004-big-game"
      priority: 7

    - name: "Mega Man 6 and The Rocketeer Speedrun"
      description: "Speedrunning event for Mega Man 6 and The Rocketeer"
      startTime: "2025-09-06T16:00:00-05:00"
      endTime: "2025-09-06T17:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Marvel vs Capcom 2 (1v1)"
      description: "1v1 Marvel vs Capcom 2 tournament"
      startTime: "2025-09-06T17:00:00-05:00"
      endTime: "2025-09-06T18:00:00-05:00"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "marvel-vs-capcom-2-1v1"

    - name: "Jay & Silent Bob: Mall Brawl and Super Dodge Ball Speedrun"
      description: "Speedrunning event for Jay & Silent Bob games"
      startTime: "2025-09-06T17:00:00-05:00"
      endTime: "2025-09-06T18:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "be quiet! Case Race"
      description: "Points activity: be quiet! Case Race"
      startTime: "2025-09-06T17:00:00-05:00"
      endTime: "2025-09-06T18:00:00-05:00"
      location: "Points area"
      type: "activity"

    - name: "Fall Guys (FFA)"
      description: "Free-for-all Fall Guys tournament"
      startTime: "2025-09-06T18:00:00-05:00"
      endTime: "2025-09-06T19:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "fall-guys-ffa"

    - name: "Marble Madness and Life Force Speedrun"
      description: "Speedrunning event for Marble Madness and Life Force"
      startTime: "2025-09-06T18:00:00-05:00"
      endTime: "2025-09-06T19:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Halo: Reach [MCC] (FFA)"
      description: "Free-for-all Halo: Reach Master Chief Collection tournament"
      startTime: "2025-09-06T19:00:00-05:00"
      endTime: "2025-09-06T20:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "halo-reach-ffa"

    - name: "Crash Bandicoot 2: Cortex Strikes Back Speedrun"
      description: "Speedrunning event for Crash Bandicoot 2"
      startTime: "2025-09-06T19:00:00-05:00"
      endTime: "2025-09-06T20:00:00-05:00"
      location: "Speedrun station"
      type: "activity"
      relatedTo: "speedrunning-stream"
      broadcast: "twitch.tv/rgblan2"

    - name: "Super Smash Bros. Melee (1v1)"
      description: "1v1 Super Smash Bros. Melee tournament"
      startTime: "2025-09-06T20:00:00-05:00"
      endTime: "2025-09-06T21:00:00-05:00"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "super-smash-bros-melee-1v1"

    - name: "Wii Tennis (2v2)"
      description: "2v2 Wii Tennis tournament"
      startTime: "2025-09-06T21:00:00-05:00"
      endTime: "2025-09-06T22:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "wii-tennis-2v2"

    - name: "Mystery game :)"
      description: "Mystery game tournament - surprise game to be revealed!"
      startTime: "2025-09-06T23:00:00-05:00"
      endTime: "2025-09-07T00:00:00-05:00"
      location: "Tournament area B"
      type: "tournament"
      relatedTo: "mystery-game"

    - name: "MIDNIGHT MADNESS!"
      description: "Special midnight event"
      startTime: "2025-09-07T00:00:00-05:00"
      endTime: "2025-09-07T01:00:00-05:00"
      location: "Main stage"
      type: "special"
      relatedTo: "midnight-madness"
      priority: 9

    # Day 3 - Sunday, September 7, 2025
    - name: "🐱Sticky Cats🐱 (FFA)"
      description: "Free-for-all Sticky Cats tournament"
      startTime: "2025-09-07T10:00:00-05:00"
      endTime: "2025-09-07T11:00:00-05:00"
      location: "Tournament area A"
      type: "tournament"
      relatedTo: "sticky-cats-ffa"

    - name: "RAFFLE!"
      description: "Prize raffle event"
      startTime: "2025-09-07T11:00:00-05:00"
      endTime: "2025-09-07T12:00:00-05:00"
      location: "Main stage"
      type: "special"
      relatedTo: "raffle"
      priority: 8

    - name: "MVP Tournament"
      description: "Most Valuable Player tournament - final championship"
      startTime: "2025-09-07T12:00:00-05:00"
      endTime: "2025-09-07T16:00:00-05:00"
      location: "Main tournament area"
      type: "tournament"
      relatedTo: "mvp-tournament"
      priority: 10

    - name: "Tournament Finals/Free Gaming"
      description: "Final tournament matches and open gaming"
      startTime: "2025-09-07T13:00:00-05:00"
      endTime: "2025-09-07T14:00:00-05:00"
      location: "Various areas"
      type: "tournament"

    - name: "LAN ENDS!"
      description: "Event conclusion and cleanup"
      startTime: "2025-09-07T14:00:00-05:00"
      endTime: "2025-09-07T15:00:00-05:00"
      location: "Main venue"
      type: "ceremony"
      priority: 10
