apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: mario-kart-world-ffa
  labels:
    game: mario-kart
    skill: casual
spec:
  name: "Mario Kart World (FFA)"
  description: "Free-for-all Mario Kart World tournament"
  eventRef: "rgb-lan-8"
  format: "free-for-all"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-06T13:00:00Z"
  endTime: "2025-09-06T14:00:00Z"
  rules:
    - "Free-for-all racing"
    - "Multiple tracks"
    - "Best overall placement wins"
  prize: "Racing trophies"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: clefairy-says-ffa
  labels:
    game: pokemon
    skill: casual
spec:
  name: "Clefairy Says (FFA)"
  description: "Free-for-all Clefairy Says tournament"
  eventRef: "rgb-lan-8"
  format: "free-for-all"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-06T15:00:00Z"
  endTime: "2025-09-06T16:00:00Z"
  rules:
    - "Simon Says style gameplay"
    - "Last player standing wins"
  prize: "Pokemon themed prizes"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: counter-strike-2-arms-race
  labels:
    game: counter-strike-2
    skill: casual
spec:
  name: "Counter-Strike 2 Arms Race (FFA)"
  description: "Free-for-all Counter-Strike 2 Arms Race tournament"
  eventRef: "rgb-lan-8"
  format: "free-for-all"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-06T16:00:00Z"
  endTime: "2025-09-06T17:00:00Z"
  rules:
    - "Arms Race mode"
    - "First to finish all weapon tiers wins"
  prize: "CS2 merchandise"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: rocket-league-3v3
  labels:
    game: rocket-league
    skill: competitive
spec:
  name: "Rocket League (3v3) Random Teams"
  description: "3v3 Rocket League tournament with random team assignments"
  eventRef: "rgb-lan-8"
  format: "bracket"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-06T17:00:00Z"
  endTime: "2025-09-06T18:00:00Z"
  rules:
    - "3v3 standard format"
    - "Random team assignments"
    - "Best of 3 matches"
  prize: "Rocket League items"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: team-fortress-2-6v6
  labels:
    game: team-fortress-2
    skill: competitive
spec:
  name: "Team Fortress 2 (6v6)"
  description: "Team Fortress 2 6v6 tournament"
  eventRef: "rgb-lan-8"
  format: "double-elimination"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-06T19:00:00Z"
  endTime: "2025-09-07T15:00:00Z"
  rules:
    - "6v6 competitive format"
    - "Standard TF2 competitive rules"
    - "Best of 3 maps"
  prize: "TF2 themed prizes"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: super-smash-bros-ultimate-1v1
  labels:
    game: super-smash-bros-ultimate
    skill: competitive
spec:
  name: "Super Smash Bros. Ultimate (1v1)"
  description: "1v1 Super Smash Bros. Ultimate tournament"
  eventRef: "rgb-lan-8"
  format: "double-elimination"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-06T20:00:00Z"
  endTime: "2025-09-06T22:00:00Z"
  rules:
    - "1v1 matches"
    - "3 stock, 7 minutes"
    - "Stage list approved"
  prize: "Gaming controllers"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: wii-tennis-2v2
  labels:
    game: wii-sports
    skill: casual
spec:
  name: "Wii Tennis (2v2)"
  description: "2v2 Wii Tennis tournament"
  eventRef: "rgb-lan-8"
  format: "bracket"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-07T09:00:00Z"
  endTime: "2025-09-07T10:00:00Z"
  rules:
    - "2v2 doubles matches"
    - "Best of 3 sets"
  prize: "Wii accessories"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: halo-reach-ffa
  labels:
    game: halo-reach
    skill: competitive
spec:
  name: "Halo: Reach [MCC] (FFA)"
  description: "Free-for-all Halo: Reach tournament"
  eventRef: "rgb-lan-8"
  format: "free-for-all"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-07T11:00:00Z"
  endTime: "2025-09-07T12:00:00Z"
  rules:
    - "Free-for-all slayer"
    - "Classic Halo rules"
  prize: "Xbox merchandise"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: pubg-ffa
  labels:
    game: pubg
    skill: competitive
spec:
  name: "PUBG (FFA)"
  description: "Free-for-all PUBG tournament"
  eventRef: "rgb-lan-8"
  format: "free-for-all"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-07T12:00:00Z"
  endTime: "2025-09-07T13:00:00Z"
  rules:
    - "Battle royale format"
    - "Last player standing wins"
  prize: "PUBG in-game items"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: marvel-vs-capcom-2-1v1
  labels:
    game: marvel-vs-capcom-2
    skill: competitive
spec:
  name: "Marvel vs Capcom 2 (1v1)"
  description: "1v1 Marvel vs Capcom 2 tournament"
  eventRef: "rgb-lan-8"
  format: "double-elimination"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-07T13:00:00Z"
  endTime: "2025-09-07T14:00:00Z"
  rules:
    - "1v1 matches"
    - "Best of 3 rounds"
    - "Tournament legal characters"
  prize: "Fighting game accessories"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: fall-guys-ffa
  labels:
    game: fall-guys
    skill: casual
spec:
  name: "Fall Guys (FFA)"
  description: "Free-for-all Fall Guys tournament"
  eventRef: "rgb-lan-8"
  format: "free-for-all"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-07T15:00:00Z"
  endTime: "2025-09-07T16:00:00Z"
  rules:
    - "Standard Fall Guys rules"
    - "Last bean standing wins"
  prize: "Fall Guys merchandise"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: counter-strike-2-wingman-2v2
  labels:
    game: counter-strike-2
    skill: competitive
spec:
  name: "Counter-Strike 2 Wingman (2v2)"
  description: "2v2 Counter-Strike 2 Wingman tournament"
  eventRef: "rgb-lan-8"
  format: "bracket"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-07T16:00:00Z"
  endTime: "2025-09-07T17:00:00Z"
  rules:
    - "2v2 Wingman mode"
    - "Best of 16 rounds"
  prize: "CS2 skins"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: super-smash-bros-melee-1v1
  labels:
    game: super-smash-bros-melee
    skill: competitive
spec:
  name: "Super Smash Bros. Melee (1v1)"
  description: "1v1 Super Smash Bros. Melee tournament"
  eventRef: "rgb-lan-8"
  format: "double-elimination"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-07T18:00:00Z"
  endTime: "2025-09-07T20:00:00Z"
  rules:
    - "1v1 matches"
    - "4 stock, no time limit"
    - "Tournament legal stages"
  prize: "Retro gaming collection"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: ut2004-big-game
  labels:
    game: unreal-tournament-2004
    skill: casual
spec:
  name: "UT2004 (big game - everyone join!)"
  description: "Large multiplayer Unreal Tournament 2004 match"
  eventRef: "rgb-lan-8"
  format: "free-for-all"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-08T10:00:00Z"
  endTime: "2025-09-08T11:00:00Z"
  rules:
    - "Large multiplayer match"
    - "All players welcome"
    - "Classic UT2004 gameplay"
  prize: "Retro FPS prizes"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: sticky-cats-ffa
  labels:
    game: sticky-cats
    skill: casual
spec:
  name: "🐱Sticky Cats🐱 (FFA)"
  description: "Free-for-all Sticky Cats tournament"
  eventRef: "rgb-lan-8"
  format: "free-for-all"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-08T11:00:00Z"
  endTime: "2025-09-08T12:00:00Z"
  rules:
    - "Cute cat-based gameplay"
    - "Family-friendly competition"
  prize: "Cat-themed prizes"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: mvp-tournament
  labels:
    game: various
    skill: competitive
spec:
  name: "MVP Tournament"
  description: "Tournament for MVP players across all games"
  eventRef: "rgb-lan-8"
  format: "championship"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-08T13:00:00Z"
  endTime: "2025-09-08T15:00:00Z"
  rules:
    - "Best players from each tournament"
    - "Cross-game competition"
    - "Ultimate champion determination"
  prize: "Grand championship trophy + cash prize"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: super-bomberman-2-ffa
  labels:
    game: super-bomberman-2
    skill: casual
spec:
  name: "Super Bomberman 2 (FFA)"
  description: "Free-for-all Super Bomberman 2 tournament"
  eventRef: "rgb-lan-8"
  format: "free-for-all"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-06T18:00:00Z"
  endTime: "2025-09-06T19:00:00Z"
  rules:
    - "Classic Bomberman gameplay"
    - "Multiple rounds"
    - "Power-ups allowed"
  prize: "Retro gaming prizes"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: marvel-rivals-6v6
  labels:
    game: marvel-rivals
    skill: competitive
spec:
  name: "Marvel Rivals (6v6)"
  description: "6v6 Marvel Rivals tournament"
  eventRef: "rgb-lan-8"
  format: "bracket"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-07T10:00:00Z"
  endTime: "2025-09-07T11:00:00Z"
  rules:
    - "6v6 team battles"
    - "Marvel hero selection"
    - "Best of 3 matches"
  prize: "Marvel merchandise"
  status: "scheduled"
  pointsRef: "tournament-points-system"

---
apiVersion: lan.party/v1
kind: Tournament
metadata:
  name: mystery-game
  labels:
    game: mystery
    skill: various
spec:
  name: "Mystery game :)"
  description: "Surprise game tournament - game revealed at event"
  eventRef: "rgb-lan-8"
  format: "surprise"
  teams: ["team-red", "team-green", "team-blue"]
  startTime: "2025-09-08T10:00:00Z"
  endTime: "2025-09-08T11:00:00Z"
  rules:
    - "Game will be revealed at the event"
    - "Fair play for all skill levels"
    - "Surprise format and rules"
  prize: "Mystery prizes"
  status: "scheduled"
  pointsRef: "tournament-points-system"
